### ISSUE TITLE
Puppeteer-extra

### ISSUE THREAD

**Issue by CorvetteCole** [xvrh/puppeteer-dart#109]
I would like to port puppeteer-extra to Dart for use with this. I have no clue where to start, but before I do, do you think this should be possible?

**Comment by g5becks** [comment]
@CorvetteCole Not the author, but if you want help, I'd be willing to contribute.

Might want to consider that this repo doesn't seem very active though, so It might be worth forking this if you cant get a response from the maintainer.

**Comment by xvrh** [comment]
Hi,
I would totally accept pull request to add high-level utility functions like the one in "puppeteer-extra".
There is already the "stealth" plugin integrated in this repo: https://github.com/xvrh/puppeteer-dart/blob/master/lib/src/plugins/stealth.dart

Feel free to ask any questions you may have.

**Comment by CorvetteCole** [comment]
I was not aware the stealth plugin was already implemented! that was my main use case, I implemented it manually with a JS file on new document load. This is very useful. @g5becks not certain I need puppeteer-extra now although it would be nice if we could use plugins built for node with this Dart library. not sure if that's feasible I'm going to look in to it

**Comment by g5becks** [comment]
@CorvetteCole no problem. It's really cool to know that this package has a plugin class built into it that can be extended though.

**Comment by MingSern** [comment]
@xvrh  Hi, I'm trying to use `puppeteer-extra` to allow my automation to sign in to google account, does the `StealthPlugin` has the functionality to bypass that? Because i'm using the `StealthPlugin` and seems like it doesn't solve my issue on Flutter side. Anyone has any suggestions?
